---
services:
    backend:
        #container_name: backend
        build:
            context: /backend
        ports:
            - 8000:8000
        depends_on:
            - chroma
    chroma:
        image: chromadb/chroma:latest
        ports:
            - "8001:8000"
        volumes:
            - chroma_data:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - PERSIST_DIRECTORY=/chroma/chroma
            - ANONYMIZED_TELEMETRY=TRUE

volumes:
    chroma_data:
