[project]
name = "internal-genius"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docling>=2.54.0",
    "fastapi[standard]>=0.117.1",
    "langgraph>=0.6.7",
]
